name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.3.0
      - name: Replace the github url
        run: |
          sed -i 's|git+ssh://git@github.com:|git+https://github.com/|g' package.json
          sed -i 's|git+ssh://git@github.com:|git+https://github.com/|g' packages/client/package.json
          sed -i 's|git+ssh://git@github.com:|git+https://github.com/|g' packages/backend/package.json
          sed -i 's|git+ssh://git@github.com:|git+https://github.com/|g' packages/sw/package.json
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: dogcraft/misskey
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
