---
name: Dockle

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  dockle:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONTENT_TRUST: 1
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Replace the github url
        run: |
          sed -i 's|ssh://git@github.com/|git+https://github.com/|g' package.json
          sed -i 's|ssh://git@github.com/|git+https://github.com/|g' packages/frontend/package.json
          sed -i 's|ssh://git@github.com/|git+https://github.com/|g' packages/backend/package.json
          sed -i 's|ssh://git@github.com/|git+https://github.com/|g' packages/sw/package.json
          sed -i 's|git@github.com:|https://github.com/|g' .gitmodules
      - run: |
          curl -L -o dockle.deb "https://github.com/goodwithtech/dockle/releases/download/v0.4.10/dockle_0.4.10_Linux-64bit.deb"
          sudo dpkg -i dockle.deb
      - run: |
          cp .config/docker_example.env .config/docker.env
          cp ./docker-compose.yml.example ./docker-compose.yml
      - run: |
          docker compose up -d web
          docker tag "$(docker compose images web | awk 'OFS=":" {print $4}' | tail -n +2)" misskey-web:latest
      - run: |
          cmd="dockle --exit-code 1 misskey-web:latest ${image_name}"
          echo "> ${cmd}"
          eval "${cmd}"
