name: Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1.0.1
      with:
        host: github.com
        private-key: ${{ secrets.SSHKEY }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: |
          packages/backend/yarn.lock
    - run: yarn install
    - run: yarn --cwd ./packages/backend lint

  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Replace the github url
      run: |
        sed -i 's|git+ssh://git@github.com:|git+https://github.com/|g' package.json
        sed -i 's|git+ssh://git@github.com:|git+https://github.com/|g' packages/client/package.json
        sed -i 's|git+ssh://git@github.com:|git+https://github.com/|g' packages/backend/package.json
        sed -i 's|git+ssh://git@github.com:|git+https://github.com/|g' packages/sw/package.json
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: |
          packages/client/yarn.lock
    - run: yarn install
    - run: yarn --cwd ./packages/client lint
