# file: .github/workflows/preview-closed.yaml
on:
  pull_request:
    types:
      - closed

name: Destroy preview environment

jobs:
  destroy-preview-environment:
    runs-on: ubuntu-latest
    if: github.repository == github.event.pull_request.head.repo.full_name
    steps:
      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Destroy preview environment
        uses: okteto/destroy-preview@latest
        with:
          name: pr-${{ github.event.number }}-syuilo
